use_frameworks!

platform :ios, '8.0'

target 'QZLicensePlateKeyboard_Example' do
  pod 'QZLicensePlateKeyboard', :path => '../'

  target 'QZLicensePlateKeyboard_Tests' do
    inherit! :search_paths

    
  end
end
